export const TOGGLE = 'TOGGLE';
export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const ADD_TO_CIRCUMSTANTIAL_MUSIC = 'ADD_TO_CIRCUMSTANTIAL_MUSIC';
export const PLAY_SELECTED_VIDEO = 'PLAY_SELECTED_VIDEO';
export const SET_MEETING_DATA = 'SET_MEETING_DATA';
export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY';
export const ADD_ENTRY_TO_MEETING = 'ADD_ENTRY_TO_MEETING';
export const PLAY_NEXT = 'PLAY_NEXT';
export const PLAY_PREVIOUS = 'PLAY_PREVIOUS';

