export const TOGGLE = 'TOGGLE';
export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const ADD_TO_CIRCUMSTANTIAL_MUSIC = 'ADD_TO_CIRCUMSTANTIAL_MUSIC';
export const SET_SELECTED_CIRCUMSTANTIAL_CELL = 'SET_SELECTED_CIRCUMSTANTIAL_CELL';
export const PLAY_SELECTED_CIRCUMSTANTIAL_VIDEO = 'PLAY_SELECTED_CIRCUMSTANTIAL_VIDEO';
export const SET_PLAYER_REF = 'SET_PLAYER_REF';
export const SET_MEETING_DATA = 'SET_MEETING_DATA';

